=== dhamaniasad/teal89-editor-repo-test/schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "object",
  "title": "My Web Site",
  "properties": {
    "Site_info": {
      "type": "object",
      "title": "Site Info",
      "properties": {
        "Favicon": {
          "type": "string",
          "title": "Favicon"
        },
        "Logo": {
          "type": "string",
          "title": "Logo"
        },
        "Copyright": {
          "type": "string",
          "title": "Copyright"
        }
      }
    },
    "Nav": {
      "type": "object",
      "title": "Nav",
      "properties": {
        "Header": {
          "type": "array",
          "title": "Header",
          "items": {
            "type": "object",
            "properties": {
              "Label": {
                "type": "string",
                "title": "Label"
              },
              "Url": {
                "type": "string",
                "title": "Url"
              },
              "Video-test": {
                "type": "file",
                "title": "video-test",
                "description": "video-test"
              }
            }
          }
        },
        "Footer": {
          "type": "array",
          "title": "Footer",
          "items": {
            "type": "object",
            "properties": {
              "Label": {
                "type": "string",
                "title": "Label"
              },
              "Url": {
                "type": "string",
                "title": "Url"
              },
              "Target": {
                "type": "string",
                "title": "Target"
              },
              "File": {
                "type": "file",
                "title": "File"
              }
            }
          }
        }
      }
    },
    "Pages": {
      "type": "array",
      "title": "Pages",
      "items": {
        "type": "object",
        "properties": {
          "Key": {
            "type": "string",
            "title": "Key"
          },
          "Heading": {
            "type": "string",
            "title": "Heading"
          },
          "Body": {
            "type": "string",
            "title": "Body",
            "format": "markdown"
          },
          "Search_enabled": {
            "type": "boolean",
            "title": "Search Enabled"
          },
          "Tags": {
            "type": "array",
            "title": "Tags",
            "description": "An array of tags",
            "items": {
              "type": "string"
            }
          },
          "Title": {
            "type": "string",
            "title": "Title",
            "description": "The SEO title of the page, for web crawlers"
          },
          "Description": {
            "type": "string",
            "title": "Description",
            "format": "textarea",
            "className": "short",
            "description": "The SEO description of the page, for web crawlers"
          }
        }
      }
    },
    "Messages": {
      "type": "object",
      "title": "Messages",
      "properties": {
        "Errors": {
          "type": "object",
          "title": "Errors",
          "patternProperties": {
            ".+": {
              "type": "object",
              "properties": {
                "Title": {
                  "type": "string",
                  "title": "Title"
                },
                "Message": {
                  "type": "string",
                  "title": "Message"
                }
              },
              "keyTitle": "Identifier"
            }
          }
        },
        "Tooltips": {
          "type": "object",
          "title": "Tooltips",
          "patternProperties": {
            ".+": {
              "type": "string",
              "keyTitle": "Identifier",
              "valueTitle": "Message"
            }
          }
        }
      }
    }
  }
}

=== dhamaniasad/teal89-editor-repo-test/data.json
{
  "Site_info": {
    "Copyright": "",
    "Favicon": "favicon.ico"
  },
  "Nav": {
    "Footer": [
      {
        "Label": "About",
        "Url": "/about"
      },
      {
        "Label": "Facebook1",
        "Url": "www.facebook.com/mywebsite",
        "Target": "_blank"
      },
      {
        "Label": "Twitter",
        "Url": "https://twitter/mywebsite",
        "Target": "_blank",
        "File": "/uploads/Screenshot from 2019-05-15 03-15-38.png"
      }
    ],
    "Header": [
      {
        "Label": "Home ",
        "Url": "/home",
        "Video-test": "/uploads/Wildlife.mp4"
      },
      {
        "Label": "Product",
        "Url": "/product"
      },
      {
        "Label": "Blog",
        "Url": "/blog"
      },
      {
        "Label": "New Header"
      }
    ]
  },
  "Pages": [
    {
      "Key": "A Page",
      "Body": "",
      "Search_enabled": true,
      "Heading": "hello",
      "Tags": [
        "foo",
        "bar",
        "hux"
      ]
    },
    {
      "Key": "Hello test",
      "Heading": "Chawal",
      "Body": "chawal ki bodya",
      "Search_enabled": true,
      "Title": "Test Seo page title",
      "Description": "some descriptions about web crawlers"
    }
  ],
  "Messages": {
    "Errors": {
      "InternalError": {
        "Title": "Internal Error",
        "Message": "An internal error occurred"
      },
      "ConnectionError": {
        "Title": "Network Error",
        "Message": "There seem to be network issues"
      },
      "Intersect Error": {
        "Title": "hello",
        "Message": "dalsdsad"
      }
    },
    "Tooltips": {
      "Welcome": "Welcome to my web site",
      "SendEmail": "click to send an email"
    }
  }
}
